# Site settings
title: Steps to Renew expired Nigerian Passport in london
email: chineduabalogu@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Basically I know the struggle I went through just trying to renew my expired Nigerian passport and unfortunately
  for me I was studying in the UK when it expired. I remember having a tough time getting the right information 
  about the process and due to inefficiency of Nigeria's management system it was a mess. I have decided to fully 
  state out the process I went through in renewing mine.
  Instead of complaining about it like everyone I met during my processing period and have decided to briefly
  illustrate the process. Hope you understand every detail.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mrabalogu_
github_username:  mrabalogu

# Build settings
markdown: kramdown

# Default settings
defaults:
-
layout: default
comments: true

